# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-07 06:27
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcement', '0010_auto_20170506_1816'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='date_expire',
            field=models.DateTimeField(default=datetime.datetime(2017, 5, 7, 9, 27, 28, 593776), verbose_name='Ημερομηνία Λήξης'),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='date_start',
            field=models.DateTimeField(default=datetime.datetime(2017, 5, 7, 9, 27, 28, 593776), verbose_name='Ημερομηνία Έναρξης'),
        ),
    ]
