# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-14 06:26
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcement', '0012_auto_20170507_1245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='date_expire',
            field=models.DateTimeField(default=datetime.datetime(2017, 5, 14, 9, 26, 31, 526178), verbose_name='Ημερομηνία Λήξης'),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='date_start',
            field=models.DateTimeField(default=datetime.datetime(2017, 5, 14, 9, 26, 31, 526178), verbose_name='Ημερομηνία Έναρξης'),
        ),
    ]
