# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-07 20:37
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcement', '0021_auto_20170528_2119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='date_expire',
            field=models.DateTimeField(default=datetime.datetime(2017, 6, 7, 23, 37, 15, 324970), verbose_name='Ημερομηνία Λήξης'),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='date_start',
            field=models.DateTimeField(default=datetime.datetime(2017, 6, 7, 23, 37, 15, 324970), verbose_name='Ημερομηνία Έναρξης'),
        ),
    ]
