# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-30 06:09
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcement', '0026_auto_20170608_0816'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='date_expire',
            field=models.DateTimeField(default=datetime.datetime(2017, 6, 30, 9, 8, 59, 702729), verbose_name='Ημερομηνία Λήξης'),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='date_start',
            field=models.DateTimeField(default=datetime.datetime(2017, 6, 30, 9, 8, 59, 702729), verbose_name='Ημερομηνία Έναρξης'),
        ),
    ]
