# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-01 21:50
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2017, 5, 2, 0, 50, 1, 440728), verbose_name='Ημερομηνία Δημιουργίας'),
        ),
        migrations.AlterField(
            model_name='contactinfo',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2017, 5, 2, 0, 50, 1, 439227), verbose_name='Ημερομηνία Δημιουργίας'),
        ),
    ]
