# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-05 06:00
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0006_auto_20170505_0842'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2017, 5, 5, 9, 0, 45, 833170), verbose_name='Ημερομηνία Δημιουργίας'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='resever_date',
            field=models.CharField(default='05/02/17', max_length=50, verbose_name='Ημερομηνία Κράτησης'),
        ),
        migrations.AlterField(
            model_name='contactinfo',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2017, 5, 5, 9, 0, 45, 828670), verbose_name='Ημερομηνία Δημιουργίας'),
        ),
    ]
