# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-07 06:27
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0010_auto_20170506_1816'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reservationinfo',
            options={'verbose_name_plural': 'Πληροφορίες σελίδας Reservation'},
        ),
        migrations.AlterField(
            model_name='contact',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2017, 5, 7, 9, 27, 28, 597276), verbose_name='Ημερομηνία Δημιουργίας'),
        ),
        migrations.AlterField(
            model_name='contactinfo',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2017, 5, 7, 9, 27, 28, 596277), verbose_name='Ημερομηνία Δημιουργίας'),
        ),
    ]
