# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-07 09:45
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0011_auto_20170507_0927'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2017, 5, 7, 12, 45, 35, 484676), verbose_name='Ημερομηνία Δημιουργίας'),
        ),
        migrations.AlterField(
            model_name='contactinfo',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2017, 5, 7, 12, 45, 35, 483175), verbose_name='Ημερομηνία Δημιουργίας'),
        ),
    ]
