# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-14 06:26
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0012_auto_20170507_1245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2017, 5, 14, 9, 26, 31, 530678), verbose_name='Ημερομηνία Δημιουργίας'),
        ),
        migrations.AlterField(
            model_name='contactinfo',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2017, 5, 14, 9, 26, 31, 529679), verbose_name='Ημερομηνία Δημιουργίας'),
        ),
    ]
