# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-24 03:19
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0013_auto_20170514_0926'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2017, 5, 24, 6, 19, 44, 872219), verbose_name='Ημερομηνία Δημιουργίας'),
        ),
        migrations.AlterField(
            model_name='contactinfo',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2017, 5, 24, 6, 19, 44, 871219), verbose_name='Ημερομηνία Δημιουργίας'),
        ),
    ]
