# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-28 17:10
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0017_auto_20170528_2005'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservationinfo',
            name='banner_text',
        ),
        migrations.RemoveField(
            model_name='reservationinfo',
            name='banner_text_eng',
        ),
        migrations.RemoveField(
            model_name='reservationinfo',
            name='banner_title',
        ),
        migrations.RemoveField(
            model_name='reservationinfo',
            name='banner_title_eng',
        ),
        migrations.RemoveField(
            model_name='reservationinfo',
            name='left_text',
        ),
        migrations.RemoveField(
            model_name='reservationinfo',
            name='left_text_eng',
        ),
        migrations.RemoveField(
            model_name='reservationinfo',
            name='left_title_eng',
        ),
        migrations.RemoveField(
            model_name='reservationinfo',
            name='right_text',
        ),
        migrations.RemoveField(
            model_name='reservationinfo',
            name='right_text_eng',
        ),
        migrations.RemoveField(
            model_name='reservationinfo',
            name='right_title_eng',
        ),
        migrations.AddField(
            model_name='reservationinfo',
            name='seo_description',
            field=models.CharField(default='Μία παραδοσιακή ψαροταβέρνα...', max_length=160),
        ),
        migrations.AddField(
            model_name='reservationinfo',
            name='seo_description_eng',
            field=models.CharField(default='Μία παραδοσιακή ψαροταβέρνα...', max_length=160),
        ),
        migrations.AddField(
            model_name='reservationinfo',
            name='seo_keywords',
            field=models.CharField(default='Εστιατόριο, Λακωνία', max_length=160),
        ),
        migrations.AddField(
            model_name='reservationinfo',
            name='seo_keywords_eng',
            field=models.CharField(default='Εστιατόριο, Λακωνία', max_length=160),
        ),
        migrations.AlterField(
            model_name='contact',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2017, 5, 28, 20, 10, 7, 533580), verbose_name='Ημερομηνία Δημιουργίας'),
        ),
        migrations.AlterField(
            model_name='contactinfo',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2017, 5, 28, 20, 10, 7, 531580), verbose_name='Ημερομηνία Δημιουργίας'),
        ),
        migrations.AlterField(
            model_name='reservationinfo',
            name='left_title',
            field=models.CharField(default='Αριστερός τίτλος στα Ελληνικά', max_length=160, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='reservationinfo',
            name='right_title',
            field=models.CharField(default='Δεξιός τίτλος στα Ελληνικά', max_length=160, verbose_name='title_eng'),
        ),
    ]
