# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-28 18:19
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0020_auto_20170528_2117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2017, 5, 28, 21, 19, 4, 48989), verbose_name='Ημερομηνία Δημιουργίας'),
        ),
        migrations.AlterField(
            model_name='contactinfo',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2017, 5, 28, 21, 19, 4, 47489), verbose_name='Ημερομηνία Δημιουργίας'),
        ),
    ]
