# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-30 06:09
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0026_auto_20170608_0816'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contact',
            options={'verbose_name_plural': '1. Κρατήσεις'},
        ),
        migrations.AlterModelOptions(
            name='contactinfo',
            options={'verbose_name_plural': '2. Επικοινωνία'},
        ),
        migrations.AlterModelOptions(
            name='contactinfopage',
            options={'verbose_name_plural': '4. Διαχείριση Πληροφορίες Contact Page'},
        ),
        migrations.AlterModelOptions(
            name='reservationinfo',
            options={'verbose_name_plural': '3. Διαχείριση σελίδας Reservation'},
        ),
        migrations.AlterField(
            model_name='contact',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2017, 6, 30, 9, 8, 59, 707729), verbose_name='Ημερομηνία Δημιουργίας'),
        ),
        migrations.AlterField(
            model_name='contactinfo',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2017, 6, 30, 9, 8, 59, 706729), verbose_name='Ημερομηνία Δημιουργίας'),
        ),
        migrations.AlterField(
            model_name='reservationinfo',
            name='left_title',
            field=models.CharField(default='Αριστερός τίτλος στα Ελληνικά', max_length=160, verbose_name='Τίτλος στα Ελληνικά'),
        ),
        migrations.AlterField(
            model_name='reservationinfo',
            name='right_title',
            field=models.CharField(default='Δεξιός τίτλος στα Ελληνικά', max_length=160, verbose_name='Τίτλος στα Αγγλικά'),
        ),
    ]
