# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-24 06:16
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0028_auto_20170908_0554'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2017, 11, 24, 8, 16, 57, 596281), verbose_name='Ημερομηνία Δημιουργίας'),
        ),
        migrations.AlterField(
            model_name='contactinfo',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2017, 11, 24, 8, 16, 57, 593781), verbose_name='Ημερομηνία Δημιουργίας'),
        ),
    ]
