# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-03 18:50
from __future__ import unicode_literals

import blog.models
import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20170503_1910'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='announcement',
            field=models.BooleanField(default=False, verbose_name='Ανακοίνωση'),
        ),
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.PostCategory', verbose_name='Κατηγορία'),
        ),
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.TextField(verbose_name='Κείμενο'),
        ),
        migrations.AlterField(
            model_name='post',
            name='content_eng',
            field=models.TextField(default='English text', verbose_name='Short description or Intro'),
        ),
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, upload_to=blog.models.upload_file, verbose_name='Εικόνα'),
        ),
        migrations.AlterField(
            model_name='post',
            name='publish',
            field=models.DateField(auto_now=True, verbose_name='Ημερομηνία Δημιουργίας'),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Τίτλος'),
        ),
        migrations.AlterField(
            model_name='post',
            name='title_eng',
            field=models.CharField(default='English tile', max_length=100, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='post',
            name='updated',
            field=models.DateTimeField(default=datetime.datetime(2017, 5, 3, 21, 50, 17, 799711), verbose_name='Ημερομηνία Event/Παρουσίασης'),
        ),
    ]
