# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-05 05:42
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20170504_0749'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='updated',
            field=models.DateTimeField(default=datetime.datetime(2017, 5, 5, 8, 42, 50, 779265), verbose_name='Ημερομηνία Event/Παρουσίασης'),
        ),
    ]
