# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-06 15:16
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20170505_0947'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='active_english',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='post',
            name='updated',
            field=models.DateTimeField(default=datetime.datetime(2017, 5, 6, 18, 16, 56, 363893), verbose_name='Ημερομηνία Event/Παρουσίασης'),
        ),
    ]
