# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-24 03:19
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_auto_20170514_0926'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='show_homepage',
            field=models.BooleanField(default=True, verbose_name='Εμφάνιση στην αρχική σελίδα'),
        ),
        migrations.AlterField(
            model_name='post',
            name='updated',
            field=models.DateTimeField(default=datetime.datetime(2017, 5, 24, 6, 19, 44, 863718), verbose_name='Ημερομηνία Event/Παρουσίασης'),
        ),
    ]
