# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-07 20:37
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0020_auto_20170528_2119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='updated',
            field=models.DateTimeField(default=datetime.datetime(2017, 6, 7, 23, 37, 15, 321470), verbose_name='Ημερομηνία Event/Παρουσίασης'),
        ),
    ]
