# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-07 22:23
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0023_auto_20170607_2356'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='updated',
            field=models.DateTimeField(default=datetime.datetime(2017, 6, 8, 1, 23, 18, 503092), verbose_name='Ημερομηνία Event/Παρουσίασης'),
        ),
    ]
