# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-08 05:16
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0024_auto_20170608_0123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='updated',
            field=models.DateTimeField(default=datetime.datetime(2017, 6, 8, 8, 16, 41, 587666), verbose_name='Ημερομηνία Event/Παρουσίασης'),
        ),
    ]
