# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-30 06:09
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0025_auto_20170608_0816'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='updated',
            field=models.DateTimeField(default=datetime.datetime(2017, 6, 30, 9, 8, 59, 691227), verbose_name='Ημερομηνία Event/Παρουσίασης'),
        ),
    ]
