# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-08 05:54
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
import mptt.fields
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0026_auto_20170630_0909'),
    ]

    operations = [
        migrations.AddField(
            model_name='postcategory',
            name='level',
            field=models.PositiveIntegerField(db_index=True, default=1, editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='postcategory',
            name='lft',
            field=models.PositiveIntegerField(db_index=True, default=1, editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='postcategory',
            name='parent',
            field=mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.PostCategory'),
        ),
        migrations.AddField(
            model_name='postcategory',
            name='rght',
            field=models.PositiveIntegerField(db_index=True, default=1, editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='postcategory',
            name='tree_id',
            field=models.PositiveIntegerField(db_index=True, default=1, editable=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='post',
            name='content',
            field=tinymce.models.HTMLField(null=True, verbose_name='Κείμενο'),
        ),
        migrations.AlterField(
            model_name='post',
            name='content_eng',
            field=tinymce.models.HTMLField(default='English text', null=True, verbose_name='Short description or Intro'),
        ),
        migrations.AlterField(
            model_name='post',
            name='updated',
            field=models.DateTimeField(default=datetime.datetime(2017, 9, 8, 5, 54, 16, 657044), verbose_name='Ημερομηνία Event/Παρουσίασης'),
        ),
    ]
