# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-30 13:43
from __future__ import unicode_literals

from django.db import migrations, models
import homepage.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutPage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(null=True, upload_to=homepage.models.upload_photo)),
                ('title', models.CharField(default='Η ΙΣΤΟΡΙΑ ΜΑΣ', max_length=150, verbose_name='Ονομασία στα Ελληνικά')),
                ('text', models.TextField(default='Greek', help_text='<p class="text">', verbose_name='Περιγραφή στα Ελληνικά')),
                ('title_eng', models.CharField(default='OUR STORY', max_length=150, verbose_name='Ονομασία στα Αγγλικά')),
                ('text_eng', models.TextField(default='English', verbose_name='Περιγραφή στα Αγγλικά')),
                ('seo_keywords', models.CharField(default='Εστιατόριο, Λακωνία', max_length=160)),
                ('seo_description', models.CharField(default='Μία παραδοσιακή ψαροταβέρνα...', max_length=160)),
                ('seo_keywords_eng', models.CharField(default='Εστιατόριο, Λακωνία', max_length=160)),
                ('seo_description_eng', models.CharField(default='Μία παραδοσιακή ψαροταβέρνα...', max_length=160)),
            ],
            options={
                'verbose_name_plural': 'About - Σχετικά Με Εμάς',
            },
        ),
        migrations.CreateModel(
            name='AboutSkills',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('icon', models.CharField(help_text='http://getbootstrap.com/components/', max_length=150)),
                ('title', models.CharField(default='Greek', max_length=60, verbose_name='Ονομασία στα Ελληνικά')),
                ('text', models.TextField(default='Greek', verbose_name='Περιγραφή στα Ελληνικά')),
                ('title_eng', models.CharField(default='English', max_length=60, verbose_name='Ονομασία στα Αγγλικά')),
                ('text_eng', models.TextField(default='English', verbose_name='Περιγραφή στα Αγγλικά')),
            ],
            options={
                'verbose_name_plural': 'About - Services on About Page',
            },
        ),
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('title', models.CharField(default='default', max_length=60)),
                ('text', models.TextField(default='default')),
                ('title_eng', models.CharField(default='default', max_length=60)),
                ('text_eng', models.TextField(default='default')),
            ],
            options={
                'verbose_name_plural': 'Homepage - Banner - Ανακοίνωσεις',
            },
        ),
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('date', models.DateTimeField()),
                ('text', models.TextField()),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='IndexPage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Εστιατόριο Ψαροταβέρνα Ο Διαμαντής', max_length=100)),
                ('active', models.BooleanField(default=True)),
                ('about_us', models.TextField(default='Greek Version', help_text='<p class="text">')),
                ('about_us_eng', models.TextField(default='English Version', help_text='<p class="text">')),
                ('seo_keywords', models.CharField(default='Εστιατόριο, Λακωνία', max_length=160)),
                ('seo_description', models.CharField(default='Μία παραδοσιακή ψαροταβέρνα...', max_length=160)),
                ('title_eng', models.CharField(default='Restatant Diamantis', max_length=100)),
                ('seo_keywords_eng', models.CharField(default='Εστιατόριο, Λακωνία', max_length=160)),
                ('seo_description_eng', models.CharField(default='Μία παραδοσιακή ψαροταβέρνα...', max_length=160)),
            ],
            options={
                'verbose_name_plural': 'Homepage - Index Page',
            },
        ),
        migrations.CreateModel(
            name='OpenHours',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Δευτέρα - Παρασκευή', max_length=150, verbose_name='Ωρες')),
                ('title_eng', models.CharField(default='Monday - Friday', max_length=150, verbose_name='Ωρες-Eng')),
                ('open', models.CharField(default='07:30', max_length=10, verbose_name='Ανοίγουμε.')),
                ('close', models.CharField(default='23:00', max_length=10, verbose_name='κλείνουμε.')),
                ('order_by', models.IntegerField(default=1, verbose_name='Κατάταξη')),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Homepage - Ωρες Λειτουργίας',
                'ordering': ['order_by'],
            },
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('icon', models.ImageField(null=True, upload_to=homepage.models.upload_photo)),
                ('title', models.CharField(default='Greek', max_length=60, verbose_name='Ονομασία στα Ελληνικά')),
                ('occupation', models.CharField(default='Greek', max_length=100, verbose_name='Απασχόληση στα Ελληνικά')),
                ('text', models.TextField(default='Greek', verbose_name='Περιγραφή στα Ελληνικά')),
                ('title_eng', models.CharField(default='English', max_length=60, verbose_name='Ονομασία στα Αγγλικά')),
                ('occupation_eng', models.CharField(default='Greek', max_length=100, verbose_name='Απασχόληση στα Αγγλικά')),
                ('text_eng', models.TextField(default='English', verbose_name='Περιγραφή στα Αγγλικά')),
            ],
            options={
                'verbose_name_plural': 'About - Προσωπικό',
            },
        ),
    ]
