# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-04 04:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='indexpage',
            name='describe',
            field=models.CharField(default='Μια οικογενιακή επειχήρηση ταν ταν', max_length=200),
        ),
        migrations.AddField(
            model_name='indexpage',
            name='describe_eng',
            field=models.CharField(default='The Seafood Restaurant has been voted by locals as "Best in the area" year after year. We actively seek out the freshest in regional seafood and produce our restaurant.Μν', max_length=200),
        ),
        migrations.AlterField(
            model_name='indexpage',
            name='title',
            field=models.CharField(default='Εστιατόριο Ψαροταβέρνα Ο Διαμαντής', max_length=100, verbose_name='Τίτλος'),
        ),
        migrations.AlterField(
            model_name='indexpage',
            name='title_eng',
            field=models.CharField(default='Restatant Diamantis', max_length=100, verbose_name='Title English'),
        ),
    ]
