# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-05 05:42
from __future__ import unicode_literals

from django.db import migrations, models
import homepage.models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0002_auto_20170504_0749'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutskills',
            name='icon',
            field=models.CharField(help_text='http://fontawesome.io/icons/', max_length=150),
        ),
        migrations.AlterField(
            model_name='staff',
            name='icon',
            field=models.ImageField(height_field=350, help_text='260*350', null=True, upload_to=homepage.models.upload_photo, verbose_name='Φωτογραφία', width_field=260),
        ),
    ]
