# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-07 09:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0004_auto_20170507_0927'),
    ]

    operations = [
        migrations.CreateModel(
            name='TableOpenTimes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Δευτέρα', max_length=30)),
                ('title_eng', models.CharField(default='Monday', max_length=30)),
                ('times', models.CharField(default='9.00-22.00', max_length=30)),
            ],
        ),
    ]
