# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-14 06:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0005_tableopentimes'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tableopentimes',
            options={'verbose_name_plural': 'Τραπέζι Ανοιχτα.'},
        ),
    ]
