# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-28 16:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0006_auto_20170514_0926'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutBanner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('title', models.CharField(max_length=50)),
                ('text', models.CharField(max_length=160)),
                ('title_eng', models.CharField(max_length=50)),
                ('text_eng', models.CharField(max_length=160)),
                ('icon', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterModelOptions(
            name='aboutpage',
            options={'verbose_name_plural': '4. About - Σχετικά Με Εμάς'},
        ),
        migrations.AlterModelOptions(
            name='aboutskills',
            options={'verbose_name_plural': '5. About - Services on About Page'},
        ),
        migrations.AlterModelOptions(
            name='banner',
            options={'verbose_name_plural': '3. Homepage - Κινούμενο Banner'},
        ),
        migrations.AlterModelOptions(
            name='indexpage',
            options={'verbose_name_plural': '1. Homepage - Index Page'},
        ),
        migrations.AlterModelOptions(
            name='openhours',
            options={'ordering': ['order_by'], 'verbose_name_plural': '2. Homepage - Ωρες Λειτουργίας'},
        ),
        migrations.AlterModelOptions(
            name='staff',
            options={'verbose_name_plural': '6. About - Προσωπικό'},
        ),
        migrations.AlterModelOptions(
            name='tableopentimes',
            options={'verbose_name_plural': '2. Homepage - Πίνακας Ανοιχτα.'},
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='aboutskills',
            name='page_related',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='homepage.AboutPage'),
        ),
        migrations.AddField(
            model_name='staff',
            name='page_related',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='homepage.AboutPage'),
        ),
        migrations.AddField(
            model_name='aboutbanner',
            name='page_related',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homepage.AboutPage'),
        ),
    ]
