# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-28 17:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0007_auto_20170528_1919'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aboutbanner',
            options={'verbose_name_plural': '7. About- Banner Text'},
        ),
    ]
