# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-28 18:06
from __future__ import unicode_literals

from django.db import migrations, models
import homepage.models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0008_auto_20170528_2005'),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuPageinfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('image', models.ImageField(null=True, upload_to=homepage.models.upload_photo)),
                ('title', models.CharField(default='Menu', max_length=150, verbose_name='Ονομασία στα Ελληνικά')),
                ('title_eng', models.CharField(default='Menu', max_length=150, verbose_name='Ονομασία στα Αγγλικά')),
                ('seo_keywords', models.CharField(default='Εστιατόριο, Λακωνία', max_length=160)),
                ('seo_description', models.CharField(default='Μία παραδοσιακή ψαροταβέρνα...', max_length=160)),
                ('seo_keywords_eng', models.CharField(default='Εστιατόριο, Λακωνία', max_length=160)),
                ('seo_description_eng', models.CharField(default='Μία παραδοσιακή ψαροταβέρνα...', max_length=160)),
            ],
            options={
                'verbose_name_plural': '4. About - Σχετικά Με Εμάς',
            },
        ),
    ]
