# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-28 18:19
from __future__ import unicode_literals

from django.db import migrations, models
import homepage.models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0010_auto_20170528_2117'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpageinfo',
            name='image',
        ),
        migrations.AddField(
            model_name='menupageinfo',
            name='image',
            field=models.ImageField(null=True, upload_to=homepage.models.upload_photo),
        ),
    ]
