# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-07 20:37
from __future__ import unicode_literals

from django.db import migrations, models
import homepage.models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0011_auto_20170528_2119'),
    ]

    operations = [
        migrations.AddField(
            model_name='indexpage',
            name='about_image',
            field=models.ImageField(null=True, upload_to=homepage.models.upload_photo, verbose_name='Είκονα About'),
        ),
        migrations.AddField(
            model_name='indexpage',
            name='menu_image',
            field=models.ImageField(blank=True, null=True, upload_to=homepage.models.upload_photo, verbose_name='Είκονα Banner'),
        ),
        migrations.AlterField(
            model_name='indexpage',
            name='title_eng',
            field=models.CharField(default='Restaurant Diamantis', max_length=100, verbose_name='Title English'),
        ),
    ]
