# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-08 05:16
from __future__ import unicode_literals

from django.db import migrations, models
import homepage.models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0015_indexpage_table_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='menupageinfo',
            name='catalogue',
            field=models.ImageField(blank=True, null=True, upload_to=homepage.models.upload_photo),
        ),
        migrations.AlterField(
            model_name='menupageinfo',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=homepage.models.upload_photo),
        ),
    ]
