# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-08 05:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0017_auto_20170630_0909'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indexpage',
            name='color_menu_hover',
            field=models.CharField(blank=True, default='#e3e3e3', help_text='Εάν το αφήσεις κενο παίρνει το αρχικό', max_length=20, null=True, verbose_name='Χρώμα menu '),
        ),
        migrations.AlterField(
            model_name='indexpage',
            name='color_menu_li',
            field=models.CharField(blank=True, default='#e3e3e3', help_text='Εάν το αφήσεις κενο παίρνει το αρχικό', max_length=20, null=True, verbose_name='Χρώμα menu επιλεγμένο'),
        ),
    ]
