# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-24 06:16
from __future__ import unicode_literals

from django.db import migrations, models
import homepage.models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0018_auto_20170908_0554'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indexpage',
            name='about_image',
            field=models.ImageField(null=True, upload_to=homepage.models.upload_photo, validators=[homepage.models.validate_image_size], verbose_name='Είκονα About'),
        ),
        migrations.AlterField(
            model_name='indexpage',
            name='menu_image',
            field=models.ImageField(blank=True, help_text='1250px*1112px', null=True, upload_to=homepage.models.upload_photo, validators=[homepage.models.validate_image_size], verbose_name='Είκονα Banner'),
        ),
        migrations.AlterField(
            model_name='indexpage',
            name='table_image',
            field=models.ImageField(null=True, upload_to=homepage.models.upload_photo, validators=[homepage.models.validate_image_size], verbose_name='Είκονα Κλείσε Τραπέζι'),
        ),
        migrations.AlterField(
            model_name='menupageinfo',
            name='catalogue',
            field=models.ImageField(blank=True, null=True, upload_to=homepage.models.upload_photo, validators=[homepage.models.validate_image_size], verbose_name='Φωτογραφία καταλόγου'),
        ),
        migrations.AlterField(
            model_name='menupageinfo',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=homepage.models.upload_photo, validators=[homepage.models.validate_image_size], verbose_name='Banner photo'),
        ),
    ]
