# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-01 21:50
from __future__ import unicode_literals

from django.db import migrations, models
import recipes.models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='black_image',
            field=models.ImageField(blank=True, null=True, upload_to=recipes.models.upload_file, verbose_name='Σκίτσο'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=recipes.models.upload_file, verbose_name='Εικόνα '),
        ),
        migrations.AlterField(
            model_name='recipecategory',
            name='black_image',
            field=models.ImageField(blank=True, null=True, upload_to=recipes.models.upload_file, verbose_name='Σκίτσο'),
        ),
        migrations.AlterField(
            model_name='recipecategory',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to=recipes.models.upload_file),
        ),
        migrations.AlterField(
            model_name='recipecategory',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=recipes.models.upload_file, verbose_name='Εικόνα'),
        ),
    ]
