# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-24 06:16
from __future__ import unicode_literals

from django.db import migrations, models
import recipes.models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_auto_20170908_0554'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='black_image',
            field=models.ImageField(blank=True, help_text='Το αρχείο πρέπει να είναι μικρότερο από 1 mb', null=True, upload_to=recipes.models.upload_file, validators=[recipes.models.validate_image], verbose_name='Σκίτσο'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='image',
            field=models.ImageField(blank=True, help_text='Το αρχείο πρέπει να είναι μικρότερο από 1 mb', null=True, upload_to=recipes.models.upload_file, validators=[recipes.models.validate_image], verbose_name='Εικόνα '),
        ),
    ]
